// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsOWBg6aLUEkv8lWEfWPM5N4foTiawh0',
    appId: '1:639544532087:web:93972aee0190aa08bcfa72',
    messagingSenderId: '639544532087',
    projectId: 'flutter-auth-23055',
    authDomain: 'flutter-auth-23055.firebaseapp.com',
    storageBucket: 'flutter-auth-23055.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB526sp558Ltdq-vK7tYQ1ffB5eHpbBSxU',
    appId: '1:639544532087:android:3619c07e633fbf79bcfa72',
    messagingSenderId: '639544532087',
    projectId: 'flutter-auth-23055',
    storageBucket: 'flutter-auth-23055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWzQSFNA072aySKG3uM4dQYKtAyJ9S66Y',
    appId: '1:639544532087:ios:61ac84c5344228aebcfa72',
    messagingSenderId: '639544532087',
    projectId: 'flutter-auth-23055',
    storageBucket: 'flutter-auth-23055.firebasestorage.app',
    iosClientId: '639544532087-ak8ottlr2voeiaj6kset2nudl90tav3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightPlateManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWzQSFNA072aySKG3uM4dQYKtAyJ9S66Y',
    appId: '1:639544532087:ios:61ac84c5344228aebcfa72',
    messagingSenderId: '639544532087',
    projectId: 'flutter-auth-23055',
    storageBucket: 'flutter-auth-23055.firebasestorage.app',
    iosClientId: '639544532087-ak8ottlr2voeiaj6kset2nudl90tav3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.weightPlateManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGsOWBg6aLUEkv8lWEfWPM5N4foTiawh0',
    appId: '1:639544532087:web:088069f3696f6b33bcfa72',
    messagingSenderId: '639544532087',
    projectId: 'flutter-auth-23055',
    authDomain: 'flutter-auth-23055.firebaseapp.com',
    storageBucket: 'flutter-auth-23055.firebasestorage.app',
  );

}